name: Build

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Frontend
        uses: actions/checkout@v4
        with:
          repository: scutrobotlab/rm-schedule-ui
          token: ${{ secrets.GH_PAT }}
          path: frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Go Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/modules') }}

      - name: inject go-build-cache into docker
        # v1 was composed of two actions: "inject" and "extract".
        # v2 is unified to a single action.
        uses: reproducible-containers/buildkit-cache-dance@v2.1.2
        with:
          cache-source: go-build-cache

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/scutrobotlab/rm-schedule:latest
            ghcr.io/scutrobotlab/rm-schedule:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/scutrobotlab/rm-schedule
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.title=rm-schedule
          cache-from: type=gha
          cache-to: type=gha,mode=max